### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by n-rodriguez** [redis-store/redis-rack-cache#12]
redis-store 1.2.0 is out : https://github.com/redis-store/redis-store/releases.
Maybe you could release a new version?

Thanks!

**Comment by tubbo** [comment]
Currently juggling some dependencies but this should be out at some point today.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by tubbo** [comment]
v2.0 has been released

**Comment by tubbo** [comment]
haha whoops forgot that PR wasn't actually merged yet, 2.0 is on its way.

**Comment by tubbo** [comment]
2.0 is out

**Comment by n-rodriguez** [comment]
thanks!
