### ISSUE TITLE
README is inconsistent/ambiguous

### ISSUE THREAD

**Issue by CaioBianchi** [redis-store/redis-rack-cache#23]
Going through the README file, one thing that caught my attention was the discrepancy between `metastore` and `entity_store` properties:

```ruby
config.action_dispatch.rack_cache = {
  metastore: ::Rack::Cache::EntityStore::Redis.new('redis://localhost:6379/0/metastore', default_ttl: 10.days.to_i),
  entity_store: ::Rack::Cache::MetaStore::Redis.new('redis://localhost:6380/0/entitystore', default_ttl: 120.days.to_i)
}
```

See `::Rack::Cache::EntityStore` and `::Rack::Cache::MetaStore`, shouldn't they be inverted?
Also is it `entity_store` or `entitystore` as the Rails-less example below illustrates?

```ruby
use Rack::Cache,
  metastore: 'redis://localhost:6379/0/metastore',
  entitystore: 'redis://localhost:6380/0/entitystore'
```

**Comment by tubbo** [comment]
You can use either `meta_store` or `metastore`. Both forms are acceptable.

**Comment by tubbo** [comment]
Pull requests are always encouraged.
