### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by vinnymac** [redis-store/redis-rack-cache#26]
If you look at the [diff](https://github.com/redis-store/redis-rack-cache/compare/v2.0.2...master) you can see that changes have been sitting around since the beginning of 2018. When can we expect to see the changes on master released in a `2.1.0` or higher?

We can always lock to a specific commit, but I don't think holding off releases this long is great either, some of the changes in master look ready to go.

Note the highest tagged version is listed as `2.0.2`, and the same is on [rubygems](https://rubygems.org/gems/redis-rack-cache) as well.

If you need help, I think Circle/Travis accounts are free for open source, and we could setup an automated deploy for this gem.

**Comment by tubbo** [comment]
@vinnymac today is your lucky day! :) think i was having some trouble releasing this and totally forgot that it needs some love. [v2.1.0](https://rubygems.org/gems/redis-rack-cache/versions/2.1.0) is out now.

**Comment by tubbo** [comment]
also, we got automated deploys so this won't happen quite as often... https://github.com/redis-store/redis-rack-cache/blob/master/.travis.yml#L18-L25
