### ISSUE TITLE
Publish 1.2.4 to Rubygems

### ISSUE THREAD

**Issue by richardvenneman** [redis-store/redis-rack-cache#8]
Hi there,

Just found that you've [bumped to 1.2.4 a few days ago](https://github.com/redis-store/redis-rack-cache/commit/e7004aa1fa3caa67ea98fa64f1c79f74719c78aa), which is great!

Could you also publish this version to RubyGems?

Thanks!

**Comment by marceloboeira** [comment]
@tubbo do you have the rubygems access to publish?

**Comment by tubbo** [comment]
@marceloboeira I do not believe so.

**Comment by marceloboeira** [comment]
@tubbo do you know who has ?

**Comment by manuelmeurer** [comment]
:+1: Would be great to get to use v1.2.4! :smile:

**Comment by manuelmeurer** [comment]
Sorry to be a PITA but could someone push 1.2.4 to Rubygems, pretty please? :smile:

**Comment by tubbo** [comment]
@manuelmeurer Apparently I do have access to push this gem now, so I just did. v1.2.4 has been deployed to RubyGems.

**Comment by richardvenneman** [comment]
:raised_hands: thanks a ton!

**Comment by manuelmeurer** [comment]
Sweet, thanks @tubbo! :+1:
