### ISSUE TITLE
redis-rack update

### ISSUE THREAD

**Issue by fgv02009** [redis-store/redis-rack-cache#9]
Hello,

I was getting this error: `cannot load such file -- rack/cache/entity_store (LoadError)`
which I fixed by bundle-updating rack-cache and requiring a version > 1.6.0 in my gemfile. I see this was accounted for in several files in commit: 604368c643311f64881aa09f6b7cf19889e92b75. I think it also needs to be updated in the gemspec which currently has this: `s.add_dependency 'rack-cache',  '~> 1.2'`

Thanks!

**Comment by tubbo** [comment]
@fgv02009 pull requests are welcome :)

**Comment by fgv02009** [comment]
Will do.

**Comment by tubbo** [comment]
@fgv02009 hey any updates on this? gonna close the issue if not.

**Comment by fgv02009** [comment]
@tubbo Sorry, I've been meaning to make a pull request and got a little distracted. You can close this. I will make a pr ASAP

**Comment by tubbo** [comment]
@fgv02009 Just reference this issue (#9) in the commit on your PR like "Fixes #9" and it'll close the issue with your commit once it's merged. :)

**Comment by marceloboeira** [comment]
Solved
